version: "3.7"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=123Abcde
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    restart: always
